### ISSUE TITLE
Detected Face always return lionel_messi

### ISSUE THREAD

**Issue by asrulsibaoel** [iamatulsingh/Face_Recognition_Tensorflow#1]
Hi, @iamatulsingh 
Congratulation for great blog post and code!
I've tried and trained your code on Paperspace (gradient notebook). I tried several images, but the result always return lionel_messi. 
Am I doing wrong or missing something? thank you.

**Comment by iamatulsingh** [comment]
Hi @asrulsibaoel 
Few questions
1) what was the training result? I mean was model trained will it some issue like over trained?
2) what was the probability of prediction?
3) how many images were in your dataset?
4) if possible, can you share your notebook?

**Comment by asrulsibaoel** [comment]
Hi @iamatulsingh 
I'm using dataset that you were reserved in dataset path. I've just testing your code and datasets nothing changed.
Here is my notebook
https://www.paperspace.com/ten3d8zl0/notebook/prbsn19tf

**Comment by iamatulsingh** [comment]
Hi @asrulsibaoel 
can you please check the confidence score of that image. I'm not able to find time to check or change anything. Please check and let me know. When I'll get some free time I'll check it too.

**Comment by iamatulsingh** [comment]
Hi @asrulsibaoel 
I've tested the code. You are right, model prediction is not correct for all images. Some of them are predicted correctly like this image `./people/cristiano_ronaldo/0ff40e065a0d430e701fb913b3f48cb1.jpg` . 
Please use pretty good dataset for training and then try it again. Also if you find any solution do let me know.

**Comment by iamatulsingh** [comment]
Hi @asrulsibaoel 
That issue has been solved and I pushed a new model architecture. Please check it.

**Comment by asrulsibaoel** [comment]
Hi @iamatulsingh 
Thank you. I'll check it soon.
