### ISSUE TITLE
InvalidArgumentError: logits and labels must be broadcastable

### ISSUE THREAD

**Issue by asrulsibaoel** [iamatulsingh/Face_Recognition_Tensorflow#2]
Hi @iamatulsingh 
I'm sorry for raising issue again.

I've added my own dataset. And got this error. I've changed these variables to my size of datasets:
```
self.BATCH_SIZE = 36
self.NUMBER_OF_TRAINING_IMAGES = 360
self.NUMBER_OF_TESTING_IMAGES = 207
```

But still got this error: 
`tensorflow.python.framework.errors_impl.InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[36,3] labels_size=[36,6]`

What I've supposed to do?

**Comment by iamatulsingh** [comment]
Hi @asrulsibaoel ,
Please try to make dataset and batch count multiple of 8. Also how many classes you have? If your classes are increased or decreased please change the dense layer in last acoording to number of classes.

**Comment by iamatulsingh** [comment]
@asrulsibaoel 
If it resolved your issue please close it.
